### PR TITLE
Add e2e code framework

### LINKED ISSUE #14: Add e2e code framework and some basic tests
Currently without some test cases, we need to test our code manully with many common cases and bug-prone.
To mitigate this, we need test cases.

### PR DESCRIPTION
**Pull request by llhuii**
try to fix #14, with other test cases to be added
 
1. Add e2e framework code stolen from k8s.io/test/e2e/framework and remove
unnecessary code for simplicity.
2. Add run-e2e.sh and a github action job to run e2e tests.
3. Add a simple dataset testcase, TODO for other CRs.
4. Update local-up.sh to support run-e2e.sh.

### CODE REVIEW

**Comment by llhuii** [comment]
And @kevin-wangzefeng help me to update the check name of "E2e test (noop now)" to "E2e test" in the settings of Sedna.

**Comment by fisherxu** [comment]
Does `make e2e` run successfully in your local host?

**Comment by fisherxu** [comment]
@llhuii

**Comment by fisherxu** [comment]
> And @kevin-wangzefeng help me to update the check name of "E2e test (noop now)" to "E2e test" in the settings of Sedna.

The Name is from github action config file, not from setting.

**Comment by llhuii** [comment]
> Does `make e2e` run successfully in your local host?

yes, I tested.

> > And @kevin-wangzefeng help me to update the check name of "E2e test (noop now)" to "E2e test" in the settings of Sedna.
> 
> The Name is from github action config file, not from setting. (noop now) maybe means run nothing now.

I mean that this pr changes the e2e checker name, so after this pr merged we need to reconfig the required e2e checker.

**Comment by fisherxu** [comment]
> > Does `make e2e` run successfully in your local host?
> 
> yes, I tested.
> 
> > > And @kevin-wangzefeng help me to update the check name of "E2e test (noop now)" to "E2e test" in the settings of Sedna.
> > 
> > 
> > The Name is from github action config file, not from setting. (noop now) maybe means run nothing now.
> 
> I mean that this pr changes the e2e checker name, so after this pr merged we need to reconfig the required e2e checker.

Get it, updated.

**Comment by JimmyYang20** [comment]
@llhuii get it.

**Pull request merged**
