### PR TITLE
[LFX'24] Add Sedna Federated Learning v2 Proposal.

### PR DESCRIPTION
**Pull request by Electronic-Waste**
**What type of PR is this?**

/kind design

**What this PR does / why we need it**:

This PR contains the proposal for Sedna Federated Learning V2 (updated version after the last community meeting).

Related to LFX'24 Fall Project: https://github.com/kubeedge/kubeedge/issues/5762

cc👀 @Shelley-BaoYue @fisherxu @tangming1996 @MooreZheng @hsj576

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by MooreZheng — CHANGES_REQUESTED** [review]
The proposal then should further consider the design of data-centric task scheduling. 

In the previous routine meeting, we see that there are challenges integrating training-operator with Sedna at the beginning: that is about what to schedule in Sedna federated learning. Since federated learning is also a training task, it is in fact data-driven. When we schedule a training task without scheduling the training data, it can lead to significant training bias. 

At the meeting, we see that there are mainly two possible ways to build a practical system. 
1. Assume that there are subnets where data can be scheduled within the same subnet.
As suggested via @tangming1996, KubeEdge itself also has node-group management that can be used to fulfill the subnet assumption. 
2. Develop a method to transfer non-raw data, e.g., embedding, where raw data can not be recovered from non-raw data.    

Besides, Kubeflow assume all training workers share the same parameter and dataset, which is not practical for edge tasks where workers have different parameters and datasets. That means we need an edge version of training operator.

**Comment by Electronic-Waste** [comment]
I've updated the proposal according to the reviews in the routine today. 

PTAL👀 @tangming1996 @MooreZheng @hsj576 @Shelley-BaoYue @fisherxu

**Review by MooreZheng — APPROVED** [review]
This proposal aims to solve a complicated issue of Sedna by considering distributed training in all different schemes. The current version is fine as the very first version after rounds of discussion. 

Note that since the whole distributed training for all schemes is undoubtedly challenging which would add tons of new features in Sedna. It is still possible to enrich in the future. As mentioned at the routine meeting, the "DataLoader DS" and the edge-wise data transfer have the potentials to be implemented with EdgeMesh @Poorunga , which should be considered in the implementation and the future version of the proposal.

**Pull request merged**
