### PR TITLE
modeloperator initial check-in

### PR DESCRIPTION
**Pull request by hxhp**
In order not to be intrusive, I added the model operator under the components folder. To avoid using nesting of modules, perhaps the root level package could be moved under the components folder as well.

### CODE REVIEW

**Comment by llhuii** [comment]
hi @hxhp , thank you for your work. There are two mainly problem about this pr:
1. What's the relation between the model crd of this model-operator and https://github.com/kubeedge/sedna/blob/main/docs/proposals/dataset-and-model.md#dataset-and-model? Can the former just replace the later?
2. This pr uses kube-builder, and its mainly code structure is so many common with the root package. I'm inclined to merge these two into one now.

**Comment by hxhp** [comment]
> hi @hxhp , thank you for your great work. There are two mainly problem about this pr:
> 
> 1. What's the relationship between the model crd of this model-operator and [this project model crd](https://github.com/kubeedge/sedna/blob/main/docs/proposals/dataset-and-model.md#dataset-and-model)? Can the former just replace the later?
> 2. This pr uses kube-builder, and its mainly code structure is so many common with the root package. I'm inclined to merge these into one in current phase.

Hi @llhuii , thank you for reviewing the PR. Please see my comments below:
1. The architecture of the model operator is different from the current root level package. Please see the architecture diagram [here](https://github.com/hxhp/sedna/tree/modeloperator/components/modeloperator). Generally, there is no LC (local controller) in the design of this PR. The whole model operator is running in the cloud, and I will make it be deployed as a Kubernetes Deployment later. (Note that it doesn't/shouldn't run on the same node as cloudcore, actually it does not talk to KubeEdge cloudcore at all. It only talks to K8s API server.) The API provided by the model operator is the InferenceModel CRD itself. Higher level operators (joint inference and etc) just create an CRD instance, and model operator will create appropriate K8s resources (jobs, pods, deployments, services) as needed. 
2. Honestly I don't think it's a good idea to merge the PR with the root level package. I think we should decouple them into separate microservices, and only use the CRD to interact with each other. And this is why I am thinking of having a components directory, where each sub directory hosts a single service. And this way we don't have to handle submodules (nesting of modules).

Please let me know what you think. Thanks.

**Comment by llhuii** [comment]
Higher level operators (joint inference and etc.) also just list and watch k8s master, like kube-controller-manager we can control these sedna operators in a binary, one microservice instead of separate microservices.

**Comment by hxhp** [comment]
> Higher level operators (joint inference and etc.) also just list and watch k8s master, like kube-controller-manager we can control these sedna operators in a binary, one microservice instead of separate binary/microservices.

Yeah I agree that a controller manager can manage more than one controllers. I am also trying to let the model operator to manage both InferenceModel and TraningModel controllers. But it looks to me that joint inference, federated learning and incremental learning are different scenarios and they have quite different operating logic. I am worried about scenarios like: Let's say we already deployed v0 of sedna in a production environment. Now we have a code change in federated learning, be it bug fix or feature improvement, and we want to deploy this change. If all these operators are in a single code base, deployed as a single binary, then all the other operators will have to be restarted. If there's a serious bug in this change, the single monolithic binary may crash, tearing down the whole system, instead of a single operator. (blast radius)

**Comment by llhuii** [comment]
We need to balance this.

> But it looks to me that joint inference, federated learning and incremental learning are different scenarios and they have quite different operating logic.

Yes, different operating logic with their own implentation go file or package, but they all belongs to Sedna.

We want simplicity for our small team at the beginning phase, single level package is simple and easy from my view.
Is sedna code base big/complicated enough for splitting into multi micro-servis?  As I can see, it is less complicated than kube-controller-manager. 

And even into multi micro-services with different kube-build generated subdirectory, hard to maintain these independent but very common files e.g. go.mod/hack/makefile.

And you suggest for splitting, what's the rule of splitting? 
1. Different scenario with different micro-service? then there would be many micro-services to maintain.

>  Let's say we already deployed v0 of sedna in a production environment. Now we have a code change in federated learning, be it bug fix or feature improvement, and we want to deploy this change. If all these operators are in a single code base, deployed as a single binary, then all the other operators will have to be restarted. 

If the users want to deploy new feature or bug, then just replace the old version with the new-released version by editing sedna deployment file. They really don't want to manitain multi versions of a package.

> then all the other operators will have to be restarted.

So what? then they can list-watch again.
> If there's a serious bug in this change, the single monolithic binary may crash, tearing down the whole system, instead of a single operator.
Then let's our release to be stable. 
Same question for kube-controller-manager, k8s, docker, linux kernel, what will they do for a bug fix?

**Comment by khalid-davis** [comment]
I think we should focus on how to locate sedna. Is sedna a collection of edge AI operators or a managers of edge AI operators? I think should be the latter. Different edge AI operators have common characteristics, not isolated ones. For example, they all need to list-watch model resources and pod resources, the SharedInformer can help us to reduce pressure on k8s if all the edge AI operators run in on process. 
> Let's say we already deployed v0 of sedna in a production environment. Now we have a code change in federated learning, be it bug fix or feature improvement, and we want to deploy this change. If all these operators are in a single code base, deployed as a single binary, then all the other operators will have to be restarted.

I think in a production enviroment, we can handle this with full testing and gray deployment.

**Pull request closed without merging**
