### PR TITLE
docs: update install guide

### PR DESCRIPTION
**Pull request by llhuii**
1. add GM/LC links
2. add GM/LC deploy form description

### CODE REVIEW

**Comment by JoeyHwong-gk** [comment]
I expect to add the installation guide for the `kb` component which  used in `LifelongLearning`.

**Comment by llhuii** [comment]
> I expect to add the installation guide for the `kb` component which used in `LifelongLearning`.

submit another pull request

**Comment by llhuii** [comment]
small update
/approve

**Pull request merged**
