### PR TITLE
LC: send dataset update to GM only when changed

### PR DESCRIPTION
**Pull request by JimmyYang20**
fix https://github.com/kubeedge/sedna/issues/136

### CODE REVIEW

**Comment by TymonXie** [comment]
“upstream numberOfSamples periodly when no update”  
pay more attention to the grammar

**Comment by JimmyYang20** [comment]
> “upstream numberOfSamples periodly when no update”
> pay more attention to the grammar

@TymonXie how about new tilte?

**Comment by llhuii** [comment]
`LC: fix upstream of number in dataset` is misleading, may means `upstream is fixed` or `number is wrong`

how about "LC: send dataset update to GM only when changed"?

**Comment by JimmyYang20** [comment]
> `LC: fix upstream of number in dataset` is misleading, may means `upstream is fixed` or `number is wrong`
> 
> how about "LC: send dataset update to GM only when changed"?

ok

**Pull request merged**
