### PR TITLE
Add all-in-one installation script

### LINKED ISSUE #21: Support all-in-one installation script on an existing k8s environment

### PR DESCRIPTION
**Pull request by llhuii**
fix #21

### CODE REVIEW

**Comment by ugvddm** [comment]
:/lgtm

**Comment by llhuii** [comment]
tested fully
/hold cancel

**Comment by JimmyYang20** [comment]
tested, successfully

**Comment by llhuii** [comment]
Instead of `git clone` here download every files under `build/crds` and `build/gm/rbac` because of large vendor directory.

**Comment by JimmyYang20** [comment]
tested it successfully

**Pull request merged**
