### PR TITLE
[federated_learning] example: change dataset and fix the interface of evaluation and inference

### PR DESCRIPTION
**Pull request by JoeyHwong-gk**
- fix the wrong dataset [#113] :  As the original image cannot distinguish between damaged and normal images, it is recommended that the GT image in the dataset can be used for training
- fix the interface of evaluation and inference

Signed-off-by: JoeyHwong <joeyhwong@gknow.cn>

### CODE REVIEW

**Review by llhuii — COMMENTED** [review]
updates in these two txt files just replace `.jpg` with `.png`, what's the difference? why do change this?

**Comment by JoeyHwong-gk** [comment]
> updates in these two txt files just replace `.jpg` with `.png`, what's the difference? why do change this?

Relate #113 , in example of federated_learning, [Magnetic-tile-defect-datasets](https://github.com/abin24/Magnetic-tile-defect-datasets.) as an open source dataset, the `png` is the GT format of  raw image suffix with `jpg`.

In our simple binary network, since the damaged （label with 1） and normal （label with 0） samples are not much different in the raw image. Replace with GT-formatted datasets can perform better in this network.

**Comment by llhuii** [comment]
> > updates in these two txt files just replace `.jpg` with `.png`, what's the difference? why do change this?
> 
> Relate #113 , in example of federated_learning, [Magnetic-tile-defect-datasets](https://github.com/abin24/Magnetic-tile-defect-datasets.) as an open source dataset, the `png` is the GT format of raw image suffix with `jpg`.
> 
> In our simple binary network, since the damaged （label with 1） and normal （label with 0） samples are not much different in the raw image. Replace with GT-formatted datasets can perform better in this network.

How can we get the GT-formatted dataset from the raw dataset? If we can, we can add the preprocess code instead of changing the dataset.
Also have we tried to change the neutral network or training parameters to improve the performance?

**Comment by JoeyHwong-gk** [comment]
> > > updates in these two txt files just replace `.jpg` with `.png`, what's the difference? why do change this?
> > 
> > 
> > Relate #113 , in example of federated_learning, [Magnetic-tile-defect-datasets](https://github.com/abin24/Magnetic-tile-defect-datasets.) as an open source dataset, the `png` is the GT format of raw image suffix with `jpg`.
> > In our simple binary network, since the damaged （label with 1） and normal （label with 0） samples are not much different in the raw image. Replace with GT-formatted datasets can perform better in this network.
> 
> How can we get the GT-formatted dataset from the raw dataset? If we can, we can add the preprocess code instead of changing the dataset.
> Also have we tried to change the neutral network or training parameters to improve the performance?

` GT-formatted dataset` has beenn provided in this dataset, follow [this paper](https://ieeexplore.ieee.org/document/8560423) , the authors show that they completed a format conversion based on a deep neural learning model by cost of hours. 
In this example, sedna considers how to improve the detection accuracy of this binary network in federated learning, and we have proved this improvement before this commit (before: 0.6263, after: 0.6383). However, because of the above problems of the dataset, the trained model always predicts "No defect" for all the images I fed into the model, as an artificial perception problems for testing.
By use the dataset in GT format which also provided by the authors, we obtain an excellent performance of 0.97, and the results are more intuitive in the model get from federated learning experiment.

**Comment by JoeyHwong-gk** [comment]
It has been closed because it has not been answered for too long. you can reopen it or submit a new one if anyone have questions.

**Pull request closed without merging**
